
public class Print_Carter_Face							// This entire class is only made in the effort to print and Dox Carter Betts' face
{
  public Print_Carter_Face()
  {
System.out.println("\n\n000000K00000000K00KK0kl;;d000000000000KKKKK000000K00kc,ckK00OkxdooooolllcclloddxxkkOo;;d0K0000000000KKKKKKKKKKKKKKk:,lOKKKKKKKKKKKKKKKKKKKKKKKKKk:,ckK\n000000KK0KKKKKK0KKOxoodxc:oO0000000KKKKKKKKKKKKKK0kdool:lxdl:;;,,,,,,''',,,',,,,;;;::::lxkkkO00000000KKKKKKKKKKK0koc;cOKK0KKKKKKKKKKKKKKKKKKKKK0xc;cOK\n0K00K00K0000K000Oxlox00K0klcoO0K00KKKKKK00KK0KK0kdodxxo:,,,,'''''''''..''''''''''''',,,,,;;;;cldkOO0KKKKKKK0K0OxooxOxlcdOKKKKKKKKKKKKKKKKKKKKOxodxd:cx\ndO000KK0KK00K0Odlok0K00K0K0kocoO0KKKKKK000KK00kocclc:;,,'''...................'''''''''''',,',,,;:cldxkO0KK0Odook0KKK0xllx0KKKKKKKKKKKKKKK0OdodO0KKOdc\noldO0KKK00K0Odlok0K0KKKKKK0K0koloO0K0KK0KKK0xl:;,,,,,'''.''...''''...............'''''''''''''''',,,,;;:ldxdlok0KKK0KKK0xllx0KKKKKKKKKKK0OdodOKKKKKKK0\n0koldOKK00Oxlok000KKKKKKK00K000koldO0K0KK0xl;,,,''''''....................................'''''''''''',,,,,;;ldxO0000K00K0xllx0KK0KKKKKOdodOKKKKKKKKKK\nKK0koldO0kllx000KK0KKKKKK00KK00K0koldO0kdc;,,,'''''................................................''''''''''',;:ldxkO00K000xllk000K0OdodOKKKKKKKKKKKK\nKKKK0kollcdOK00KK00KKKK00KKK00000K0xccc;,,''''''............................................................''''',,;:cldxO000Odlok0Odlok0KKKKKKKKKKKKK");
System.out.println("KKKKKKOc':kKKKKKKKKKKK000K0000000Oxl:,''''.............................'',,;;;;;;;;,,'..........................'''''',,;:lxO00Odllclk0K0KKKKKKKKKKKKK");
System.out.println("KKKKKK0o,;xKKKKKKKKKKK000000KK0Odc;,''''......................',,;:clooooollcc::;;,,''...............................''',,',:oOKKx,'o0KKKKKKKKKKKKKKKK");
System.out.println("KKKKKOxoc;lOKKKKKKKK0KK0000K0Odc,''''.......''..........',:clodxdoolc::,''............................................'''''''':d0x:,o0KKKKKKKKKKKKKKKK");
System.out.println("KK0OdodkOxlcdOKKKKKKK0000K0Od:,''''........;c;....',:codxkkxolc;,'........................................................''''',col;ckKKKKKKKKKKKKKKKK");
System.out.println("KOdodO0KKK0xlldO0KK0000K0Od:,''..........,od:'',coxO0Oxol:;''.................................................................''';dkocoOKKKKKKKKKKKKKK");
System.out.println("dldO0KKKKKKK0koloO0KKKKOdc,'''.........'ck0kddxO00kdl:,'..........................................................................;okkoloOKKKKKKKKKKKK");
System.out.println("dOKKKKKKKKKKKKKOdldOK0xc,'''..........,oOKKKKK0kdc;'...............................................................................';d0OdldOKKKKKKKKKK");
System.out.println("KKKKKKKKKKKKKKKKKOdllc;'''............cO0K0Okdc;'....................................................................................;xK0OdldOKKKKKKKK");
System.out.println("KKKKKKKKKKKKKKKKKKkc,'''..............;lolc:,'........................................................................................cOKK0kolx0KKK0Od");
System.out.println("KKKKKKKKKKKKKKKKOd:,''.................................................................................................................o0K0K0kook0Odox");
System.out.println("KKKKKKKKKKKKKK0xc,''...................................................................................................................;kKK00K0xoccdOK");
System.out.println("KKKKKKKKKKKKK0o;''......................................................................................................................cOK00KK0o';xKK");
System.out.println("KKKKKKKKKKKKKd;'........................................................................................................................'lOKKKK0o;ckKK");
System.out.println("KKKKKKKKKKKKx:'............................'''''''...'''',,,,,;;;;;;;;;,,,,,,,'''........................................................,o0K0kddl:lOK");
System.out.println("x0KKKKKKKK0x;'........................'''''''''''''''',,,,,;;;;;;;;,,,,,,,,,,,,,,,,,,,,,'................................................';dkoox00klco");
System.out.println("oox0KKKKKKx;'.............................               .......'',,,;;;,,,,,,,,,,,,,,,,,,,,,,,'........................................''',lk0KKKK0ko");
System.out.println("0kook0KKKOc'......................                                 ....',,,,,,,,,,,,,,,,'',,,',,,,,''.......................     .........'':kKKKKKKKK");
System.out.println("KK0kookK0o,'................                                             ....',,,,,,,''',,''''''''''',,,''....................        ......'cOKKKKKKK");
System.out.println("KKKKKxooo;'..............                                                      ...',,,,'''''''''''''''''''''''.................         .....,l0KKKKKK");
System.out.println("XXXXXKKx;'............                                                             ..'',,'''''''''''''''''''''''''.................     ......;xKKXXXX");
System.out.println("XXXXXKXk;..........                                                                    ...',''''''''''''''''''''''''''...  ...........  ......'c0XKXXX");
System.out.println("XXKKKKKd,........                                                                         ...'','''''''''''''''''''''''''...  ......... .......,dKXXXX");
System.out.println("KKKKKOd;.......                                                                               ..'''''''''''''''''''''''''.....    .....   ......cOXKKK");
System.out.println("XXKkddc.. ...                                         .....                                      ...''''''''.'''''''''''''''.....    ..    .....,dKKKK");
System.out.println("KkddkKx'...                                     .............                                       ...''''.......'''''''''........         .....cOKKK");
System.out.println("ddOKXX0c..                                   .........................                                 ...'''.........'.'''...........       ....;xKKK");
System.out.println("OXXXXX0c.                                  ...........................         ..                         ...'''......'''................     ...'o0KK");
System.out.println("XXXXXOc..                                .............................      ......                           ...'''....''...'............  .......:kOx");
System.out.println("XXXXk:.                               .............................................                             ......'.................     .....'cdx");
System.out.println("XXXk:.                               ....................................................                           ...............',;;..     .....cOK");
System.out.println("XXOc.                               ..........................................................                         ..........',;clc;..     ...'xK0");
System.out.println("XKl..                             ......................................................................   ..................',;:llloll:,..      .,kK0");
System.out.println("Xx,.                                 ..................................................................................''',;;::cloooool:,'..      ,xKK");
System.out.println("x:.                                    ............................................................................''',,;;;:ccccloooool:;''..     .:d0");
System.out.println("l.                .....                  .......................'''......'......................................'',,,;;:::clllllooooool:;'...     .lol");
System.out.println("o.          ...............                    ...........''''''''''''''''''''.............................'''',,,,;;::cccloooooooooool:;'....    .xKk");
System.out.println("l.         .'...',;'.......                           .......'''''''''',,,,,''''''''''''.....'''..'''''''''''',,,,,;;;::cclooddddoooool:;'....    .dKK");
System.out.println("d.      ...''..';cc;,''...        ....                  ........''',,,,,,,,,,,,',''''''''''''''''..........''....'''',,;;:ccloddddoooolc;'.....   .xKK");
System.out.println("0d;'..,:lc;,'..':loc;;,'....................       ..............'',,,,,,,,,,,,,,,,,,,,,,,''''''.......................''',;;:lddddooolc;'.....   'kK0");
System.out.println("XNKkooddoc,'...,codoc::;'........................................'',,;;;;;;;;,,,,,,,,,,,,,,,,,''........        ...........',;:codddoool;'.....   :0KK");
System.out.println("NXKkl:cc:,'...';cddollc:;,'''''''''''''''''..................''.''',,;;;;;;;;,,,,,,,,,,,,,,,''''..........      ............',,;cloddool:'.....  .xKKK");
System.out.println("NXKxc,,,,,'...,;ldxdoolc:;,,,,,,,''''......................'''''''',,;;;;;,,,,,,,,,,,,,,,,,,'''.............................''',;cloddooc,.......oXXKK");
System.out.println("NXXOl,',,,'..';:oxxddolc::;;;,,,'............... .............''''',,,,;;,,,,;;,,,,,,,,,,,,'''''''''........'''''''''''','''''',,:codddoc,......lKNNX0");
System.out.println("NNKko:,,:;,..,,:oxxxdolc::;;,,'.......   ..           ..........'',,,,,;;;;;;;;;;;;;;;;,,,,,'''''............''''''',,,,,,,,,,,,;:codddol,.....,xNNNX0");
System.out.println("Xkxxdl;:ol;'',;cdxxxdolc::;,,'.....   ...'..       .   ...........',,,,;;;;;;;:::;;;;;;,,,,,''.......................'',,,,;;;;::clodxddl;......cOKXXK");
System.out.println("kkkOxocoddl;'';lxxxxdollc::;,,''........'''.  .    . ..'..........',,,;;;;;;;::::;;;;;;,,,''...........     ............'',,;;::cllodxxdl;......,oxO0O");
System.out.println("k0K0Ododdoc:,,:dxxxxddollcc::::::;;,,''...'..... ....',,'.....''''',,;;;;;;::::::;;;:;;,,,''..........          ...  ......',;::cclodxxdo;'.....':cldo");
System.out.println("OOkkkxdolc:;,,cxxxxxddoollccccccccc:::;,,,'''........''.......',,,,,;;:::::::cccc::::;;,,,'''''.....,.  .       .,'..    ...',;::cloddxxo:,''....',col");
System.out.println("kkkkkxdoc:;;,;lxkxxxddoooollcc:::::::::::;;;,,,,','''''''''''',,;,;;:::::::::cccllcc:;,;;,,,;,'.....''..........,,''...'...',,;;::cloddxdc,''....':odd");
System.out.println("xxxxkxdolc::;:okkxxxddddoolccc::::;;;;;;;;;;,,,,,,'''''''''',,;;;;::::cc:::cccclllccc::::;;;;;,,,,,,,,,,'''',,;;;;;;;::cccccccclllloodxxdl;'.','',lxkk");
System.out.println("xxxxxxxdoc:::coxkxxxddddoolllcc:::;;;;;;;;,,,,,,''',''',,,;;:::::::::cccccccccllllllccc:::::;;;;,,',,,,,,,;;;;::::::ccclllloooooooddddxxdl;'';:;,:oxxx");
System.out.println("ddddxxxddoc::coxkxxxddddooollccc::::;;:;;;;;;;;;;;;::::::::ccccccccccccccllllclllllllcccccccc:::;,,,''''',,,;;;;;:::::ccccloodddddddddxxxl;',clc:ldxxx");
System.out.println("dddddxdddddooloxkxxxdddooooollllccc:::c:::::::::::cccccccccccccccccclccllllllcllllllllccclcccclllcc::;;,,,,,,,,,;;;;::clllooddddooddddxxxo;';cloloxxxx");
System.out.println("llooodxddddxxxxxkxxxddddooooooolllllccllcccccccccccccccccccccccccclllllllllllllllllooollllllllllllllllcc::::::::cccllloooooddddoooooddxxxo;';:looddddd");
System.out.println(":::ccodxxxxxkxxxkxxxxdddooooodoooollllllllllllllllcccccccccclccllllllllllllllllllloooollloollllllloooooooollcclllllooooodddddoooooooddxxxo;,;:loddolll");
System.out.println(";;;;;cdxxxxxxxxkkkkxxdddddddddddddooooollllllllllllllccllllllllllllllllllllllllllooooooolooolllllloooooooooooooooddddddddddddooooooodddxxo:;:clodo::c:");
System.out.println("''''',lxxxxxxxxkkkkxxxddddddddddddooooooooolllllllllllllllllllllllllcccllllllllllloddooooooooooooooooooooooddddddddddxxxddddddoooodddddxxl::cooddc;,,,");
System.out.println("......,oxxxxxxxxkkkxxxdddxxddddddooooooooollllllllllllllllllllllllllllooooooooooooodddoooooooooooooooooooooooddddddddxxxxxdddddddddddddxxlclooodo;'.''");
System.out.println(".......,coodddddxkxxxxdddddddddddoooooooooolllllllllllllllccclccllllooooooooooooodddddooooooooolooooooodddddoddddddddddxxxxxxdddddddddxxxdooooddc'....");
System.out.println(",;,;;;;;:;;:cllloxxxxxxddddddddddooooooooooollllllllllcccccclllllloooooooddddddddddddddoooooolllcloooooooddddoodddddddddxxxxxxxxxxddddxxxxxdddddc,,,,,");
System.out.println(";;;;;::;'.''',::lxxxxddddddddooooooooooooollllcccccc::::cclllllooooooddddddddddddddddddooooooollccclloooooodddddddddodddxxddxxxxxxxxxxxxxxxxxxdolccccc");
System.out.println(";;;;;,'.';;;,'',cxxddddddodddooooooooolllllccc:::;;;;;;;:loooodddddddddddddddddddddddddooddoooooc::::clllloooooddddddddddddddddddddxxxxxxxxxxxdoccc:cc");
System.out.println(";:;,''';;;:;::;';dkxdddoddooooooooooolllccc::;;,,,;;:::::looooooooooooodddddddooooooooooooooddool:;;;;::ccclooooooooooooodddoddddddxxxxxxxxxxdoc:c::::");
System.out.println(":;,',;::;;;;:::;cdkxdoooooooooooooolllcc::;;,,,,;;::cccc::ccc::::cclllloooooolllllllllllllllooool:;;;;,,;;:cclllooooooolooooooddodddxxxxxdddoolcccc:::");
System.out.println(",';:::;::::::::::okxdooooooooollllllcc:;;,,'',,;;::ccc:cc::;,,.....',;clllllllccccc:::;;;;;::::cc::::;;;,,;;:cccllllllloooooooooooddddxxdllllcc:cc:::;");
System.out.println(",;::::::::::::;;:okkddoooollllllccc::;;,'''',,,;;:::cccccc::;;,'''''.',;cc:::::;;;;,........,;;::::::::;;,,,,;::ccllllllloolloooooodddxxlc:,;ccc:cc;;;");
System.out.println(":::::::::::::::::lxkxdoooollllccc::;,,''''',,;;;:::ccccccccc:::;;;;;;;;;;:::;;,,;;,'.....''',;::::::::;;;;,,,,,;:ccccccllllllllllloodxxoc::;,,;c:;,;::");
System.out.println(";;;;;;:::;;;:::::cdxxddoooollc::;,,''.''',,;:::cccllllllllllcc:::::;;;;;;,,,,,,,,,,',,,,,,;;;::cc:::;::;;;;,,,,,;:::cccccclllllllllooxxl:::::;,',;::::");
System.out.println(";;;;;;;::;;::;:::coxxxddddoolc:,'''''''',,;;:cclllllllolooooollcc::;;;,,,'''''''''',,,;;;::ccclcccc::cc:;;;,,,,,,;:::c:::ccccccclllodxxlc:cccc,.,ccccc");
System.out.println(":::::::::c:c::::::lxxxddddddoc:;,'',,''',,;;;:ccllllllooooooooolllc:::;,,,'''''''',,;;::ccllllllllllllccc:;;;,,,,,,;:::::::::ccccclodxoc::cccc;'':ccc:");
System.out.println(":c::::::::::::::::cdxxddddddolc::;,,,,,,'.....',,;::cccclloloooooollcccc::;;;;;;::::ccllllloooooolollllccc:;;,,,,,,,,;;:::::cccccclodxl:c::cc::;,,;cc:");
System.out.println(";;:cc:::::::::::;:cldxdddddddoolc::;;;;;,'..      ..',,;;:::ccccccccccclccccccclccllllllllllllllllllllcc::;;,,,,,,,,,,;;::::cccccllodoccccc:::ccc:;;:c");
System.out.println("c:;;:cc::ccccc::::::oxddddddddoolcc::::::::;,..    .',;;:::;;;;;;:::;;;;;;;::::;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,',,;,',;;::cccccclloddlclc::::ccc::::;;");
System.out.println("cccc::cccclllcc:::ccldddddddddooollccc:cccllc:,'.  .';::ldol::cc:;;;;;;,,,,,,,,'',,,,,,,,,'',,,'....     ....'',,;,',;:cccclllllllodlccc:::::ccccccll:");
System.out.println("dddddolclodxdoccldxxxxdddddddddoooolllllllloooc:;,...':coxxdoldxdocclllc::,,,;;::::;;;:cc:;:cc:,,'..     ...,;;;;;;;:cllllllllllllddllodxxxxxxxxxxxxxx");
System.out.println("xxxxxxxdlcllccldxxxxxxxdddddddooooooooooooooooollcc;'..';lddl:oxxxddkkkxxdollodxxxxdlldxdlcoddc;;,.   ..',:::::::::cllolllllllllloolldxxxxxxxxxxxxxxxk");
System.out.println("dddddddddo;';odddddddddddoddddoooooooooooooodddoollllc:;,;c;..;looclkkkkxxxdxxxkkkkxodxxdloddl;,'...',,;:ccccccclllooooollolllllolldxxddxxxdddddddddxx");
System.out.println("oooooooool,.;odddoooooddddddddooooooooooooddddddddollolllcc:,,;;;;;:lddddolcldxxxxdc;cll;.,c:'..'';:::ccllcllllloooooooolllllllll:cdxxxxxxdddddddddddd");
System.out.println("oooooooodoc;,:oddoddddddddddddoooooooddddddddddddddolllooooollc:;;;;;:ccc:;,;:ccccc:,;c:,.';;;;:ccccccllllllllooooooolllllllllooc,:dxxxdxxxddddddxdddd");
System.out.println("oooooooolcclc::cooooodoooodddoooooodddddddddddoodddddoollooooooollcc::::::;;;::;;::::::c:ccllllllccclllllloooooooooolllllllcloollc;:oxxxxxxddxxxxxxxxx");
System.out.println("oodddoc:cloodolcccooddddooddkxdoooooddddddddddddddddddoollllooooooooooolllllllllllllllloooooollccccllllllooooooooollllllllllllodxxdlccodxxxxdxddxxxxxd");
System.out.println("oodoc:cooooooooooc:coddoodk0KOxddoodddddddddddddddoooodooollllllllllllloooooooodddoooooooollccccllllllllooooooooollcclllllllodxxxxxxxoccoxxxxxxxxxxxxx");
System.out.println("dlcclodddddddddddddollodk000Okxdodddddooooddxxxxxddoooodddooollccc::::cccccccclllccccccccccccllloolllllooooddoolllccllccloddxxxxxxxxxxxoccoxxxxxxxxxdo");
System.out.println("cclddddddddddddddddddoodkOkkxolldxddddddddddxxxxxxdddooooooooollccc::;;;;;;;;;;;::::::::cccllollllllooooodddooolcclllclldxxxxxxxxxxxxxxxdocloxxxxxdolo");
System.out.println("odddddddddddddddddddx00dlodocldxxxxddddddddxxxxxxxxdddooollllllcccc::;;;;;;;;;;;;;:::ccccllllllllloooddddddooollllccclodxxxxxxxxxxxxxxxxxxdlclddollodx");
System.out.println("xxxxxxxkxxxxxxxxkkxxkkxxdc;:oxxxxxkxdddddddxxxxxkxxxdddooolllllccc::::::;;;;;:::::::ccccccccccllooddddddddooollllcccoddxxxxxxxxxxxxxxxxxxxxxdl:;:oxxxx");
System.out.println("kkkkkkkkkkkkkkkkkkkkkkkkd:,cdkkkkkkxxxddddddxxxkkkxxxxdddddoooollllcccc::::::::::ccccccccccllloodddddddddoollllcclooddxkOkOOOOOOOOOOOOOOOOOOOo''lOOOOO");
System.out.println("kkkkkkkkkkkkkkkkkkkkkkkkko::okkkkkkxxxxdddoddxxxxkkxxxxddddddddddoooooollloooollllllllllloooooddddddddoooolllcclooddddxO000OOOOOOOOOOOOOOOOOOxc;lkOOOO");
System.out.println("cdxxxxxxxxxxxxxxxxxxxxxolool:coxxxxxxxxxxdooodddxxxkkxxxdxxxdddddddddddddddddddddddddddddddddddddddddooolllccloodddddxdodxxxxxxxxxxxxxxxxxxxoooc;:oxxx");
System.out.println("llldxxxxxxxxxxxxxxxxdoloddxxdolloxkxxxxxxxddoooddxxxxxxxddxxxxxdddxdddddddddddooodddddddddddxxxxxdddoolllcclloooddddddxo:oxxxxxxxxxxxxxxxxolodxxdl:cox");
System.out.println("xdolldOK0kxxxxxxxxdllodxxxxxxxxdloxxxxxxxxxxddooddddxxxxxxxxxxxxxxddxxdddddddoooodddddddddxxxxxxddoollccclloooddddddddxxc;dxxxxxxxxxxxxxolodxxxxxxdocc");
System.out.println("oloxkddkkkxxxxxxdllodxxxxxxxxxxxooxkxxxxxxxddddddooddddxxxxxxxxxddddddddddddddoddddddddddddxddddollccccllooooddddddddddxo,:kxxxxxxxxxxolodxxxxxxxxxxdl");
System.out.println("dx0XK0xoldxxxxdllodxxxxxxxxxxxOkllxkxxxxxxxxxxxxddddoooddddddddddooooooooooodddddddddddddddooollccccclloooooddddddddddxxx:.oOxxxxxxdolodxxxxxxxxxxxxxx");
System.out.println("KXK0OkkxdlodollodxxxxxxxxxdddO0d:lxkkxxxxxxxxxxxdddddoolooooooooooollllllooooooooollloddooollcccccllloooooooddddddddddxxxl.;kkddxxolodxxxxxxxxxxxxxxxx");
System.out.println("K0Okkkkkkko:;lxkkkkkkkkkdlodxOOl,cxkkxxxxxxddddxxddddddoollccclccccccccccllllllllllclllllcccccllllloooooooooooddddddddxxxo,.lOxodl;:coxxxxxxxxxxxxxxxx");
System.out.println("Okkkkkkkkkl',lkkkkkkkkxlldOkx0x:'cxkkkkxxxxdddddddddddddddoollc:::::::::::ccccccccccc::::::cllooooooooooooooodddddddddxxxd;.;xOodxo,..':ldxxxxxxxxxxxx");
System.out.println("OOkkkkkkkkdc;:okkkkOOdcoO0Oxk0o;':dxxxxxxxxxxxddddddddddxxxdddoolcc::::;;;;;;:;;;;::::::ccllloooooooooooooooddddddddddxxxd;.,cOklxOkl,...;lxxxxxxxxxxx");
System.out.println("kkkkkkkkxooddlldkkOko:oO00kx0kc;,:oxxxxxxxxxxxddddddddddddddddddooollcc:::;;;;;;;;:::cccllllooooooooooooooddddddddddddxxdo;.,;dOookOOkl' .'cxxxxxxxxxx");
System.out.println("kkkkkkxoldxkkxxxxkko;lk000kk0o;;;:odxxxxxxxxxxxddddddddddddddddddooolllccc::::::::cccclllllooooooooooooooddddddddddddddddl,';;cOxlxOOOkd;. 'lxxxxxxxxx");
System.out.println("kkkkdoodxkkxddxxxkd::dO00Ok0k:,;;:ldxxxxxxxxxxxxxdddddddddddddddoooollllccccccccccccclllllllooololllooooooddddddddddddddo:'';,c0OldOOOOkd:.'lxkkxxxxxx");
System.out.println("kxdoodxxkkkxxddkkxc,cxOO0OO0o',,;:lodxxxxxxxxxxxxxxxddddddddddddoooollllllcccccccccccllllllllllllllloooooddddddddddddddoc;',;,oK0lokOOOkxo:cldkkkkxdoo");
System.out.println("dccllccoxkkdooxkkd;,lxOOOO0k:'',:cclodxxxxxxxxxxxxxxddddddddddddoooollllllllccccccccclllllllllllllloooooddddddddddddddol:,',;;xN0ookOkkxoollodxxkkxlod");
System.out.println(";,,,',cdxkxdooxkxl,,oxkOOOOd,.',:ccloddxxxxxxxxxxxxxxddddddddddddooollllllcccccccccccllllllllllloooooooooddddddddddddol:;',;,:ON0ookkkxdollllodxxxxdl:");
System.out.println("'''.':odxxdoodxkxc';oxkOOOkc..',;:clooddxxxxxxxxxxxxxxdddxxxddddddooolllllcccccccccccllllllloooooooooooooddddddddddool:;,,,,,lKNOlokkxolllllodxxxkxdo;");
System.out.println("....'ldxkxdooxxxo,':oxkOOOk;...,;:clloddxxxxxxxxxxxxxxxxxxxxddddddoooollllccccccccllllllloooooooooooooooddddddddddoolc:,,,,,;xXXxcoxolllllodddxxxxkxdd");
System.out.println("....:ddxkxddddkxc.':oxkkOOx,...',;:cllodddxxxxxxxxxxxxxxxxddddddddooooollllllllllllllllllooooooooooddoodddddddddddool:;,,,,,cON0ocoolllododddddddxkkxd");
System.out.println("...,odxkkddoodxxl,,:odkkOOd,..'',;:cllooddddxxxxxxxxxxxxxddddddddddooooolllllllllllllooooooooooooooddddddddddddddoolc:,,,,,,lKN0l:lolloddxdddoodxxxxkx");
System.out.println(". .cooxkkxddoxkxd:,:odxkkOd,.''',;:cclloodddxxxxxxxxxxxxxxxxddddddddooooooooollllllloooooooooooooooddddddddddddddoll:;,,,,,,dXNOlcoolodddxddoodxxdxkkk"); 
  }
}
